apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - start: "192.168.100.31"
      stop: "192.168.100.39"
  allowFirstLastIPs: "No"  # Required in Cilium 1.16+ if reserving first/last IPs 
