apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: "192.168.100.0/24"  # Use "blocks" instead of "cidrs" Usable IPs: 192.168.101.17 to 192.168.101.30
    - start: "192.168.100.31"
      stop: "192.168.100.39"
  allowFirstLastIPs: "No"  # Required in Cilium 1.16+ if reserving first/last IPs 
