apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - rotoapi.tomkor.home
  rules:
    - host: rotoapi.tomkor.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rotoapi
                port:
                  number: 5555